# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 030859171ee2deb5c51a67881b463970b6350de166453b8f129badb0a8622bcb6bb3940555689cbdfc71a44aa379a3478cfd590086002b4b1af78dca88889a58

test:
  secret_key_base: e3f7101e6d050f5e0212d73fbfde93efe1a971d65267afe9c87aac3ecf6ab373cdd1263a26e8df3c12af8b56dd46fb9bdab72295b893e62ca3d766c65e2a5fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
